#!/usr/bin/env python3
# coding: utf-8


"""Concatenate SPDE simulation outputs for downstream processing."""

import numpy as np
import sys, os
import pickle
from numpy import linalg as LA
import gc, os, re, sys
from collections import defaultdict
from typing import Tuple
from scipy.interpolate import interp1d
from functions.SpectralDecomposition import calculate_A
from functions.intersect_time import intersect_time
import numpy as np
from scipy.interpolate import PchipInterpolator



# Load workflow paths from environment variables.
import  Module_get_envname
SPDE_DIR = Module_get_envname.SPDE_DIR
CONCATENATE_DIR = Module_get_envname.CONCATENATE_DIR
STDOUT_DIR = Module_get_envname.STDOUT_DIR + "/stdout_concatenate.txt"
INTERIM_DIR = Module_get_envname.INTERIM_DIR
PHASE_DIR = Module_get_envname.PHASE_DIR
# Example invocation with explicit paths:
# ```
# CONCATENATE_DIR=/path/to/save STDOUT_DIR=logs/concat.txt python SRC/Calculate_Concatenate_SPDEdatas.py
# ```

if __name__ == '__main__':

    # Redirect standard output to the workflow log.
    original_stdout = sys.stdout
    sys.stdout = open(STDOUT_DIR, 'w')
    os.makedirs(CONCATENATE_DIR, exist_ok=True)

    try:

        # Load simulation data generated by Simulate_CoupledModel.py.
        if not os.path.isdir(SPDE_DIR):
            raise FileNotFoundError(
                f"Simulation data directory not found. Checked '{SPDE_DIR}'.")


        # Select debug files when requested; otherwise select production files.
        use_debug_files = os.environ.get("USE_DEBUG_FILES", "0").lower() in ("1", "true", "yes")

        if use_debug_files:
            data_files = [
                f for f in os.listdir(SPDE_DIR)
                if f.endswith('.npz') and 'debug' in f.lower()
            ]
            print(f"Targeting debug-only data files (name contains 'debug'): {len(data_files)} found", flush=True)

        else:
            data_files = [
                f for f in os.listdir(SPDE_DIR)
                if f.endswith('.npz') and 'debug' not in f.lower()
            ]
            print(f"Targeting non-debug data files (name lacks 'debug'): {len(data_files)} found", flush=True)


        # Group entries by initial state, epsilon, and sigma.
        grouped_files = defaultdict(list)
        pattern = re.compile(
            r"(?:debug_)?state(\d+)_([0-9]+)_eps([0-9.eE+-]+)_sig([0-9.eE+-]+)_process_(\d+)"
        )


        for file_path in data_files:
            base_filename = os.path.splitext(os.path.basename(file_path))[0]
            match = pattern.search(base_filename)
            if not match:
                continue

            init_a_idx = int(match.group(1))
            init_b_idx = int(match.group(2))
            eps_val = float(match.group(3))
            sigma_val = float(match.group(4))
            proc_val = int(match.group(5))
            grouped_files[(init_a_idx, init_b_idx, eps_val, sigma_val)].append((proc_val, file_path))

        # Sort each group by process number.
        for key in grouped_files:
            grouped_files[key].sort()

        if not grouped_files:
            print("No simulation data matched the expected pattern.", flush=True)


        # Process each initial-state, epsilon, and sigma combination.
        for (init_a_idx, init_b_idx, eps_val, sigma_val), file_entries in grouped_files.items():
            print(
                f"Processing init_a_idx: {init_a_idx}, init_b_idx: {init_b_idx}, eps: {eps_val}, sigma: {sigma_val}",
                flush=True,
            )

            # Select the output filename.
            if use_debug_files:
                save_filename = f"debug_concatenated_state{init_a_idx}_{init_b_idx}_eps{eps_val}_sig{sigma_val}.npz"
            else:
                save_filename = f"concatenated_state{init_a_idx}_{init_b_idx}_eps{eps_val}_sig{sigma_val}.npz"
            target_path = os.path.join(CONCATENATE_DIR, save_filename)


            # Skip output that already exists.
            if os.path.isfile(target_path):
                print(f"  → skipped (file already exists): {target_path}", flush=True)
                continue

            # Accumulate time-series arrays.
            all_eps_t = []
            all_U1_bar, all_U2_bar = [], []
            all_V1_bar, all_V2_bar = [], []
            all_A1_tilde, all_A2_tilde = [], []
            all_moments_t = []
            last_rx = None

            # Load each time-series segment in process order.
            for _, file_path in file_entries:
                print(f"  → using file: {file_path}", flush=True)
                datas = np.load(os.path.join(SPDE_DIR, file_path))

                moments_t = datas["moments_t"].ravel()
                if moments_t.size == 0:
                    print("    (skip: moments_t empty)", flush=True)
                    continue

                all_U1_bar.append(datas["U1_bar"])
                all_U2_bar.append(datas["U2_bar"])
                all_V1_bar.append(datas["V1_bar"])
                all_V2_bar.append(datas["V2_bar"])
                all_A1_tilde.append(datas["A1_tilde"])
                all_A2_tilde.append(datas["A2_tilde"])
                all_moments_t.append(moments_t)
                all_eps_t.append(eps_val * moments_t)
                last_rx = datas["rx"]

            if last_rx is None or not all_moments_t:
                print("  → skipped (no usable data)", flush=True)
                continue
            
            # Concatenate process segments.
            simulation_data = {
                "U1_bar": np.concatenate(all_U1_bar, axis=0),
                "U2_bar": np.concatenate(all_U2_bar, axis=0),
                "V1_bar": np.concatenate(all_V1_bar, axis=0),
                "V2_bar": np.concatenate(all_V2_bar, axis=0),
                "A1_tilde": np.concatenate(all_A1_tilde, axis=0),
                "A2_tilde": np.concatenate(all_A2_tilde, axis=0),
                "t": np.concatenate(all_moments_t),
                "eps_t": np.concatenate(all_eps_t),
                "rx": last_rx
            }

            np.savez(target_path, **simulation_data)
    finally:
        # Restore standard output.
        sys.stdout.close()
        sys.stdout = original_stdout
